# https://files.minecraftforge.net/net/minecraftforge/forge/
modLoader = "javafml"
loaderVersion = "[46,)"
license = "GPL-3"
issueTrackerURL="https://github.com/p0t4t0sandwich/Template/issues"

[[mods]]
modId = "template"
version = "${file.jarVersion}"
displayName = "Template"
updateJSONURL="https://raw.githubusercontent.com/p0t4t0sandwich/Template/main/forgeUpdates.json"
displayURL="https://github.com/p0t4t0sandwich/Template"
logoFile="Template.png"
credits="p0t4t0sandwich"
authors="p0t4t0sandwich"
displayTest="IGNORE_SERVER_VERSION"
description = '''
Template
'''

# Forge Dependency
[[dependencies.template]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

# Minecraft Dependency
[[dependencies.template]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"
