name: Template
version: '${version}'
author: p0t4t0sandwich
description: Template
main: dev.neuralnexus.template.bukkit.BukkitTemplatePlugin
depend: []
folia-supported: true
commands:
  template:
    description: Template
    usage: /template
    permission: template
