name: Template
version: '${version}'
author: p0t4t0sandwich
api-version: 1.13
main: ca.sperrer.p0t4t0sandwich.template.bukkit.BukkitMain
description: Template
folia-supported: true
commands:
  template:
    description: Template
    usage: /template
    permission: template
